apiVersion: v1
kind: ConfigMap
metadata:
  name: productsuppliermagaluworker
  namespace: catalog-integration-qa
data:
  Consul__Key: qa/catalog/integrations/product/supplier/magalu
  ConnectionStrings__HangFire_Storage:   configmap.yaml: should be well protected
