apiVersion: v1
kind: ConfigMap
metadata:
  name: productchangeworker
  namespace: catalog-integration-qa
data:
  Consul__Key: qa/catalog/integrations/product/change
  ConnectionStrings__Integration:   configmap.yaml: should be well protected
