apiVersion: v1
kind: ConfigMap
metadata:
  name: sharedapps
  namespace: catalog-integration-dev
data:
  DOTNET_ENVIRONMENT: Production
  ASPNETCORE_ENVIRONMENT: Production
  ASPNETCORE_URLS: http://+:80
  ConnectionStrings__ServiceBus: Endpoint=sb://   configmap.yaml: should be well protected
  Consul__Address: http://az-us-dev-consul-01.labmac.corp:8500
  Consul__Token: NoEntropy'sHere
  Logging__AzureEventHub__Environment: dev
  Logging__AzureEventHub__ConnectionString: Endpoint=sb://macmarketplaceeventhubdev01.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=Some-Token-Shared
