---
apiVersion: v1
kind: Secret
metadata:
  name: <<NOME DO PROJETO>>
  namespace: <<NOME DO NAMESPACE>>
type: Opaque
stringData:
  EXEMPLO_SECRET_1: 'valor1'
  EXEMPLO_SECRET_2: 'valor2'
  EXEMPLO_SECRET_3: 'valor3'