##############################################################################
# ARQUIVO YAML DE CONFIGURACAO DO CRONJOB NO OPENSHIFT QUE DISPARA PERIODICAMENTE
# O SHELL PARAMETRIZADO QUE EH CARREGADO ATRAVEZ D EUM CONFIGMAP
#
# O SCRIPT SHELL EXECUTADO ESTA ABAIXO
# http://gitlab.macna.local/infraestrutura/PBM/p1m-reposicao-medicamento-batch/blob/master/configmap/gerarpedido-DEV.sh
#
# Macnaima Macnamara
# 11/FEV/2020
#
# AMBIENTE: OEPNSHIFT DEV
##############################################################################


apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: post-gerarpedido
spec:
  #  min / hora / dia do mes / mes / dia da semana
  #  ex: 0 0 * * *             -> executa todos os dias às 00:00 horas
  #      00 14 10 3,6,9,12 *   -> executa às 2:00PM no dia 10 de Março, Junho, Setembro e Dezembro
  #      25,50 1 15 * 2        -> executa às 1:25AM e às 1:50AM toda Terça e no 15º dia de todo mês
  schedule: "*/5 * * * *"
  # valores possíveis: Allow, Replace, Forbid
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      successfulJobsHistoryLimit: 2
      failedJobsHistoryLimit: 1
      template:
        metadata:
          labels:
            parent: "cronjob-post"
        spec:
          containers:
          - name: post-gerar-pedido
          # PARA OS DEMAIS AMBIENTES, ALTERAR A IMAGEM ABAIXO DE ACORDO
            image: docker-registry.default.svc:5000/default/alpine-base-custom:latest
            args:
               - /bin/bash
               - -c
               - |
                 /scripts/gerarpedido.sh $(DISTRIBUIDORAS)

            volumeMounts:
               - name: wrapper
                 mountPath: /scripts
            env:
            - name: DISTRIBUIDORAS
              valueFrom:
                configMapKeyRef:
                  name: distribuidoras
                  key: distribuidoras

          volumes:
          - name: wrapper
            configMap:
              name: cronjob-gerarpedido
              defaultMode: 0777


          restartPolicy: OnFailure