version: '3.4'

services:
  integration.api:
    image: ${DOCKER_REGISTRY-}integrationapi
    build:
      context: .
      dockerfile: Integration.Api/Dockerfile
    container_name: Integration.Api

  integration.mongo:
    image: mongo
    container_name: Integration.Mongo
