parameters:
  - name: AppName
    type: string

  - name: DeploymentEnvironment_DEV
    type: string

  - name: DeploymentEnvironment_QA
    type: string

  - name: DockerfilePath
    type: string

  - name: ContainerRegistry
    type: string

  - name: ImageRepository
    type: string

  - name: ImageTag
    type: string

  - name: ImagePullSecret
    type: string

  - name: DockerRegistryServiceConnection
    type: string

  - name: VmImage
    type: string

stages:
  - template: 'build-stage.yml' # Build
    parameters:
      Stage: Build
      StageDisplayName: Build
      Appname: ${{ parameters.AppName }}
      DockerfilePath: ${{ parameters.DockerfilePath }}
      ImageRepository: ${{ parameters.ImageRepository }}
      ImageTag: ${{ parameters.ImageTag }}
      DockerRegistryServiceConnection: ${{ parameters.DockerRegistryServiceConnection }}
      VmImage: ${{ parameters.VmImage }}

  - template: 'deploy-stage.yml' # Deploy DEV
    parameters:
      Stage: Deploy_DEV
      StageDisplayName: Deploy DEV
      DependsOn:
        - Build
      EnvironmentName: DEV
      DeploymentEnvironment: ${{ parameters.DeploymentEnvironment_DEV }}
      Appname: ${{ parameters.AppName }}
      ContainerRegistry: ${{ parameters.ContainerRegistry }}
      ImageRepository: ${{ parameters.ImageRepository }}
      ImageTag: ${{ parameters.ImageTag }}
      ImagePullSecret: ${{ parameters.ImagePullSecret }}
      DockerRegistryServiceConnection: ${{ parameters.DockerRegistryServiceConnection }}
      VmImage: ${{ parameters.VmImage }}

  - template: 'deploy-stage.yml' # Deploy QA
    parameters:
      Stage: Deploy_QA
      StageDisplayName: Deploy QA
      DependsOn:
        - Build
      EnvironmentName: QA
      DeploymentEnvironment: ${{ parameters.DeploymentEnvironment_QA }}
      Appname: ${{ parameters.AppName }}
      ContainerRegistry: ${{ parameters.ContainerRegistry }}
      ImageRepository: ${{ parameters.ImageRepository }}
      ImageTag: ${{ parameters.ImageTag }}
      ImagePullSecret: ${{ parameters.ImagePullSecret }}
      DockerRegistryServiceConnection: ${{ parameters.DockerRegistryServiceConnection }}
      VmImage: ${{ parameters.VmImage }}
