apiVersion: v1
kind: ConfigMap
metadata:
  name: productsagaworker
  namespace: catalog-integration-qa
data:
  Consul__Key: qa/catalog/integrations/product/saga
  ConnectionStrings__Integration: mongodb://aplicCatIntegrMacnaim:macn@mongodb.qa.machinacorp.com.br:27017/CatalogIntegration?authSource=admin
