@echo off&setlocal enabledelayedexpansion
for /f "tokens=2 delims= " %%a in ('date /t') do set data=%%a
set data=%data:/=-%
ren PREFECHAMENTO_LOG.TXT %data%_PREFECHAMENTO_LOG.TXT
ren PREFECHAMENTO_ERRO.TXT %data%_PREFECHAMENTO_ERRO.TXT
ren FECHAMENTO_LOG.TXT %data%_FECHAMENTO_LOG.TXT
ren FECHAMENTO_ERRO.TXT %data%_FECHAMENTO_ERRO.TXT
dir
copy /Y C:\CMDLOG\*PREFECHAMENTO_LOG.TXT C:\CMDFI\FICLOSE\mail
copy /Y C:\CMDLOG\*PREFECHAMENTO_ERRO.TXT C:\CMDFI\FICLOSE\mail
copy /Y C:\CMDLOG\*FECHAMENTO_LOG.TXT C:\CMDFI\FICLOSE\mail
copy /Y C:\CMDLOG\*FECHAMENTO_ERRO.TXT C:\CMDFI\FICLOSE\mail
dir
move /Y C:\CMDLOG\*PREFECHAMENTO_LOG.TXT C:\CMDLOG\HISTORICO
move /Y C:\CMDLOG\*PREFECHAMENTO_ERRO.TXT C:\CMDLOG\HISTORICO
move /Y C:\CMDLOG\*FECHAMENTO_LOG.TXT C:\CMDLOG\HISTORICO
move /Y C:\CMDLOG\*FECHAMENTO_ERRO.TXT C:\CMDLOG\HISTORICO
dir